### ISSUE TITLE
Plugin doesn't work with gatsby-plugin-mdx

### ISSUE THREAD

**Issue by a2jimenez** [sititou70/gatsby-remark-related-posts-example#1]
I am a newbie with Gatsby. I installed this plugin, it shows that it's creates the vectors:
[gatsby-remark-related-posts]  bow vectors generated, dimention:  236

but don't see it in graphql under AllMdx

**Comment by sititou70** [comment]
Thank you for trying this plugin. And sorry, I have not tested this plugin with MDX so I thought the plugin needed some additional changes to work with MDX.

Could you please provide me the test code (the code you are trying this plugin locally) to fix the plugin? The code should be minimal for this matter. In other words, if there is text in the code that you want to keep secret, you can replace it with dummy text, and you can delete plugins that are not related to this matter.

regards

**Comment by sititou70** [comment]
@a2jimenez 
I updated the plugin to v2 and corresponded to mdx.
please check the sample repo: https://github.com/sititou70/gatsby-remark-related-posts-example-mdx
