### ISSUE TITLE
I cannot integrate this plugin with Strapi CMS

### ISSUE THREAD

**Issue by adityanagar10** [sititou70/gatsby-remark-related-posts-example#2]
Hello, 

In your documentation you've mentioned

` posts_dir: `${__dirname}/posts`,`

but I don't know how should I do the same for strapi. Can you help me with that?

**Comment by sititou70** [comment]
thank you for using my package. Currently, this package does not support strapi. However, I would like to support it in the future. The work may take some time. sorry

**Comment by sititou70** [comment]
@adityanagar10

Sorry for the late reply.
I updated the plugin to v2 and corresponded to strapi.
Check sample repo: https://github.com/sititou70/gatsby-remark-related-posts-example-strapi

**Comment by adityanagar10** [comment]
@sititou70 Thanks a lot for spending your time and effort on this. This was really helpful
